Error on unknown options instead of treating as command args
Previously, typos like --hots instead of --host would silently
be passed as command arguments to the container. Now any
argument starting with - that isn't recognized triggers an
error with helpful guidance.

diff --git a/claudo b/claudo
--- a/claudo
+++ b/claudo
@@ -173,6 +173,11 @@ while [[ $# -gt 0 ]]; do
             command_args=("$@")
             break
             ;;
+        -*)
+            echo "Error: Unknown option '$1'" >&2
+            echo "Run 'claudo --help' for usage information" >&2
+            exit 1
+            ;;
         *)
             command_args+=("$1")
             shift
